// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: BUSL-1.1

package template

import (
	"github.com/Masterminds/sprig/v3"
)

// funcMap contains all supported template functions.
var funcMap = map[string]any{}

func init() {
	springFuncs := sprig.HermeticTxtFuncMap()
	for _, k := range allowedSprigFuncs {
		if _, ok := springFuncs[k]; ok {
			funcMap[k] = springFuncs[k]
		} // missing functions are detected in Test_funcMap()
	}
}

// allowedSprigFuncs contains the set of all sprig functions allowed. it is a
// subset of sprig.HermeticTxtFuncMap, with all crypto related functions being
// removed. It should only contain functions that are both secure and fit to
// purpose.
var allowedSprigFuncs = []string{
	"abbrev",
	"abbrevboth",
	"add",
	"add1",
	"add1f",
	"addf",
	"adler32sum",
	"ago",
	"all",
	"any",
	"append",
	"atoi",
	"b32dec",
	"b32enc",
	"b64dec",
	"b64enc",
	"base",
	"bcrypt",
	"biggest",
	"buildCustomCert",
	"camelcase",
	"cat",
	"ceil",
	"chunk",
	"clean",
	"coalesce",
	"compact",
	"concat",
	"contains",
	"deepCopy",
	"deepEqual",
	"default",
	"dict",
	"dig",
	"dir",
	"div",
	"divf",
	"duration",
	"durationRound",
	"empty",
	"ext",
	"fail",
	"first",
	"float64",
	"floor",
	"fromJson",
	"get",
	"has",
	"hasKey",
	"hasPrefix",
	"hasSuffix",
	"htpasswd",
	"indent",
	"initial",
	"initials",
	"int",
	"int64",
	"isAbs",
	"join",
	"kebabcase",
	"keys",
	"kindIs",
	"kindOf",
	"last",
	"list",
	"lower",
	"max",
	"maxf",
	"merge",
	"mergeOverwrite",
	"min",
	"minf",
	"mod",
	"mul",
	"mulf",
	"mustAppend",
	"mustChunk",
	"mustCompact",
	"mustDeepCopy",
	"mustFirst",
	"mustFromJson",
	"mustHas",
	"mustInitial",
	"mustLast",
	"mustMerge",
	"mustMergeOverwrite",
	"mustPrepend",
	"mustPush",
	"mustRegexFind",
	"mustRegexFindAll",
	"mustRegexMatch",
	"mustRegexReplaceAll",
	"mustRegexReplaceAllLiteral",
	"mustRegexSplit",
	"mustRest",
	"mustReverse",
	"mustSlice",
	"mustToDate",
	"mustToJson",
	"mustToPrettyJson",
	"mustToRawJson",
	"mustUniq",
	"mustWithout",
	"nindent",
	"nospace",
	"omit",
	"osBase",
	"osClean",
	"osDir",
	"osExt",
	"osIsAbs",
	"pick",
	"pluck",
	"plural",
	"prepend",
	"push",
	"quote",
	"randInt",
	"regexFind",
	"regexFindAll",
	"regexMatch",
	"regexQuoteMeta",
	"regexReplaceAll",
	"regexReplaceAllLiteral",
	"regexSplit",
	"repeat",
	"replace",
	"rest",
	"reverse",
	"round",
	"semver",
	"semverCompare",
	"seq",
	"set",
	"sha1sum",
	"sha256sum",
	"shuffle",
	"slice",
	"snakecase",
	"sortAlpha",
	"split",
	"splitList",
	"splitn",
	"squote",
	"sub",
	"subf",
	"substr",
	"swapcase",
	"ternary",
	"title",
	"toDecimal",
	"toJson",
	"toPrettyJson",
	"toRawJson",
	"toString",
	"toStrings",
	"trim",
	"trimAll",
	"trimPrefix",
	"trimSuffix",
	"trimall",
	"trunc",
	"tuple",
	"typeIs",
	"typeIsLike",
	"typeOf",
	"uniq",
	"unset",
	"until",
	"untilStep",
	"untitle",
	"upper",
	"urlJoin",
	"urlParse",
	"values",
	"without",
	"wrap",
	"wrapWith",
}
