{{- /*
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1
*/ -}}

{{- if .Values.csi.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-%s" (include "vso.chart.fullname" .) "aggregate-role-viewer-csi-driver" }}
  labels:
    app.kubernetes.io/component: rbac
    vso.hashicorp.com/role-instance: aggregate-role-viewer
    rbac.authorization.k8s.io/aggregate-to-view: "true"
{{- include "vso.chart.labels" . | nindent 4 }}
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        vso.hashicorp.com/aggregate-to-viewer: "true"
{{- end -}}
