{{/*
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1
*/}}

{{- if .Values.csi.enabled -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-%s" (include "vso.chart.fullname" .) "csi-driver-role" }}
  labels:
    app.kubernetes.io/component: rbac
    # allow for selecting on the canonical name
  {{- include "vso.chart.labels" . | nindent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - pods
    - serviceaccounts
    - configmaps
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - pods/status
  verbs:
    - get
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
    - patch
- apiGroups:
    - ""
  resources:
    - serviceaccounts/token
  verbs:
    - create
    - get
    - list
    - watch
{{- end -}}
