{{/*
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1
*/}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-%s" (include "vso.chart.fullname" .) "proxy-role" | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/component: controller-manager
  {{- include "vso.chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-%s" (include "vso.chart.fullname" .) "proxy-rolebinding" | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/component: controller-manager
  {{- include "vso.chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s-%s" (include "vso.chart.fullname" .) "proxy-role" | trunc 63 | trimSuffix "-" }}
subjects:
- kind: ServiceAccount
  name: {{ printf "%s-%s" (include "vso.chart.fullname" .) "controller-manager" | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
