---
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultSecret
metadata:
  name: vaultsecret-test-tenant-1
spec:
  namespace: vault-tenant-1
  mount: kvv2
  type: kvv2
  name: secret
  dest: secret1
  refreshAfter: 5s
