# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

# permissions for end users to edit csisecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: csisecrets-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vault-secrets-operator
    app.kubernetes.io/part-of: vault-secrets-operator
    app.kubernetes.io/managed-by: kustomize
  name: csisecrets-editor-role
rules:
- apiGroups:
  - secrets.hashicorp.com
  resources:
  - csisecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.hashicorp.com
  resources:
  - csisecrets/status
  verbs:
  - get
