# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# permissions for end users to view vaultpkisecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaultpki-viewer-role
rules:
- apiGroups:
  - secrets.hashicorp.com
  resources:
  - vaultpkisecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets.hashicorp.com
  resources:
  - vaultpkisecrets/status
  verbs:
  - get
