# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# permissions for end users to edit vaultpkis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaultpki-editor-role
rules:
- apiGroups:
  - secrets.hashicorp.com
  resources:
  - vaultpkis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.hashicorp.com
  resources:
  - vaultpkis/status
  verbs:
  - get
