sprite $pod [64x62/8] {
__________________________uu0000000uuu__________________________
______________________uu00024KaaaSC42000uu______________________
__________________uu00024KaaaaaaaaaaaaK42000uu__________________
______________uu00034KaaaaaaaaaaaaaaaaaaaaK43000uu______________
__________uu0013CSaaaaaaaaaaaaaaaaaaaaaaaaaaaaSC3100uu__________
______uu0013CSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaSC3100uu______
_____001CSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaSC00u_____
_____00SaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaK00_____
____00Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa100____
____00SaaaaaaaaaaaaaaaaaaaZYWOG88GOWYZaaaaaaaaaaaaaaaaaaaJ00____
___001aaaaaaaaaaaaaZYXWG8000000000000008GWXYZaaaaaaaaaaaaa10u___
___00KaaaaaaaaaaaaaQJ4321000000000000001234JQaaaaaaaaaaaaaJ00___
__u01aaaaaaaaaaaaaa0008GOXQB43211234BQXOG8000aaaaaaaaaaaaaa10u__
__00Jaaaaaaaaaaaaaa00000000008OZYO80000000000aaaaaaaaaaaaaaB00__
_u01aaaaaaaaaaaaaaa000000000000RI000000000000aaaaaaaaaaaaaaa00u_
_00Jaaaaaaaaaaaaaaa000000000000RI000000000000aaaaaaaaaaaaaaaA00_
u00aaaaaaaaaaaaaaaa000000000000RI000000000000aaaaaaaaaaaaaaaS00_
00Aaaaaaaaaaaaaaaaa000000000000RI000000000000aaaaaaaaaaaaaaaaA00
00Saaaaaaaaaaaaaaaa200000000000RI000000000002aaaaaaaaaaaaaaaaS00
00aaaaaaaaaaaaaaaaaaaK310000000RR000000013KaaaaaaaaaaaaaaaaaaZ00
008YaaaaaaaaaaaaaaaaaaaaSC30000RR00003CSaaaaaaaaaaaaaaaaaaaaY800
_700OaaaaaaaaaaaaaaaaaaaaaaaK42RR24KaaaaaaaaaaaaaaaaaaaaaaZO007_
___008XaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaX007___
____700GZaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaZG007____
______700XaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaO007______
_______7008YaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaY800________
_________700OZaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaZO007_________
___________000XaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaX007___________
____________700GZaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaZG007____________
______________700OZaaaaaaaaaaaaaaaaaaaaaaaaaaZO007______________
_______________700000000000000000000000000000007________________
}
