sprite $secret [64x62/8] {
__________________________uu0000000uuu__________________________
______________________uu00024KaaaSC42000uu______________________
__________________uu00024KaaaaaaaaaaaaK42000uu__________________
______________uu00034KaaaaaaaaaaaaaaaaaaaaK43000uu______________
__________uu0013CSaaaaaaaaaaaaaaaaaaaaaaaaaaaaSC3100uu__________
______uu0013CSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaSC3100uu______
_____001CSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaSC00u_____
_____00SaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaK00_____
____00Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa100____
____00Saaaaaaaaaa88888Iaaa888888888888888888888aaaaaaaaaaJ00____
___001aaaaaaaaaaa33333Jaaa3333A99A3333333333333aaaaaaaaaaa10u___
___00KaaaaaaaaaaaaaaaaaaaaYO00000000OYaaaaaaaaaaaaaaaaaaaaJ00___
__u01aaaaaaaaaaaaaaaaaaaaG0003CKKB3100GaZZZZZZZaaaaaaaaaaaa10u__
__00JaaaaaaaaaaaaaaaaaaaQ002SaaaaA0P200I1000000aaaaaaaaaaaaB00__
_u01aaaaaaaaaaaaaaaaaaPGGGGGGGGGGGGGGGGGGPKCCCCaaaaaaaaaaaaa00u_
_00Jaaaaaaaaaaaaaaaaaa90000000000000000009aaaaaaaaaaaaaaaaaaA00_
u00aaaaaaaaaaaaaaaaaaa90000000144100000009YXXXXaaaaaaaaaaaaaS00_
00Aaaaaaaaaaaaaaaaaaaa90000000QaaQ0000000990000aaaaaaaaaaaaaaA00
00Saaaaaaaaaaaaaaaaaaa90000000088000000009SSSSSaaaaaaaaaaaaaaS00
00aaaaaaaaaaaaaaaaaaaa90000000000000000009aaaaaaaaaaaaaaaaaaaZ00
008YaaaaaaaaaaaaaOOOOOJ444222222222222222IOOOOOaaaaaaaaaaaaaY800
_700Oaaaaaaaaaaaa11111Iaaa111111111111111111111aaaaaaaaaaaZO007_
___008XaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaX007___
____700GZaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaZG007____
______700XaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaO007______
_______7008YaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaY800________
_________700OZaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaZO007_________
___________000XaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaX007___________
____________700GZaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaZG007____________
______________700OZaaaaaaaaaaaaaaaaaaaaaaaaaaZO007______________
_______________700000000000000000000000000000007________________
}
