sprite $vol [64x62/8] {
__________________________uu0000000uuu__________________________
______________________uu00024KaaaSC42000uu______________________
__________________uu00024KaaaaaaaaaaaaK42000uu__________________
______________uu00034KaaaaaaaaaaaaaaaaaaaaK43000uu______________
__________uu0013CSaaaaaaaaaaaaaaaaaaaaaaaaaaaaSC3100uu__________
______uu0013CSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaSC3100uu______
_____001CSaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaSC00u_____
_____00SaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaK00_____
____00Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa100____
____00SaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaJ00____
___001aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa10u___
___00KaaaaaaaaaaaaZXWWOG8880000000000888GOWWXZaaaaaaaaaaaaJ00___
__u01aaaaaaaaaaaO000000000000000000000000000008Oaaaaaaaaaaa10u__
__00JaaaaaaaaaaaH320000000000000000000000000123HaaaaaaaaaaaB00__
_u01aaaaaaaaaaaa008GOOH9A23333333333332A9GOOG800aaaaaaaaaaaa00u_
_00Jaaaaaaaaaaaa00000000000000000000000000000000aaaaaaaaaaaaA00_
u00aaaaaaaaaaaaa00000000000000000000000000000000aaaaaaaaaaaaS00_
00Aaaaaaaaaaaaaa00000000000000000000000000000000aaaaaaaaaaaaaA00
00Saaaaaaaaaaaaa30000000000000000000000000000003aaaaaaaaaaaaaS00
00aaaaaaaaaaaaaaaaSC443211100000000001112344CSaaaaaaaaaaaaaaaZ00
008YaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaY800
_700OaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaZO007_
___008XaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaX007___
____700GZaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaZG007____
______700XaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaO007______
_______7008YaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaY800________
_________700OZaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaZO007_________
___________000XaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaX007___________
____________700GZaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaZG007____________
______________700OZaaaaaaaaaaaaaaaaaaaaaaaaaaZO007______________
_______________700000000000000000000000000000007________________
}
