# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

---
apiVersion: v1
kind: Pod
metadata:
  name: app1
  namespace: tenant-1
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: secrets
          mountPath: "/etc/secrets"
          readOnly: true
  volumes:
    - name: secrets
      secret:
        # created in Terraform
        secretName: pki1
        optional: false # default setting; "mysecret" must exist
#---
#apiVersion: secrets.hashicorp.com/v1alpha1
#kind: VaultPKISecret
#metadata:
#  namespace: tenant-2
#  name: vaultpkisecret-sample-tenant-2
#spec:
#  namespace: cluster1/tenant-2
#  mount: pki
#  name: default
#  destination:
#    name: pki1
#  commonName: consul.example.com
#  revoke: false
#  format: pem_bundle
#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: app1
#  namespace: tenant-2
#spec:
#  containers:
#    - name: nginx
#      image: nginx
#      volumeMounts:
#        - name: secrets
#          mountPath: "/etc/secrets"
#          readOnly: true
#  volumes:
#    - name: secrets
#      secret:
#        # created in Terraform
#        secretName: secret1
#        optional: false # default setting; "mysecret" must exist
#
