# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

---
apiVersion: v1
kind: Secret
metadata:
  name: secret1
  namespace: tenant-1
type: Opaque
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: tenant-1
  name: vaultstaticsecret-sample-tenant-1
spec:
  # namespace: cluster1/tenant-1
  vaultAuthRef: vaultauth-sample
  mount: kvv2
  type: kv-v2
  path: secret
  refreshAfter: 5s
  destination:
    name: secret1
---
apiVersion: v1
kind: Secret
metadata:
  name: secret1
  namespace: tenant-2
type: Opaque
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: tenant-2
  name: vaultstaticsecret-sample-tenant-2
spec:
  # namespace: cluster1/tenant-2
  vaultAuthRef: vaultauth-sample
  mount: kvv1
  type: kv-v1
  path: secret
  refreshAfter: 5s
  destination:
    name: secret1
---
apiVersion: v1
kind: Pod
metadata:
  name: app1
  namespace: tenant-1
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: secrets
      mountPath: "/etc/secrets"
      readOnly: true
  volumes:
  - name: secrets
    secret:
      secretName: secret1
      optional: false # default setting; "mysecret" must exist
---
apiVersion: v1
kind: Pod
metadata:
  name: app1
  namespace: tenant-2
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: secrets
      mountPath: "/etc/secrets"
      readOnly: true
  volumes:
  - name: secrets
    secret:
      secretName: secret1
      optional: false # default setting; "mysecret" must exist
