# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: vaultpkisecret-tls
  namespace: tenant-1
spec:
  vaultAuthRef: vaultauth-sample
  namespace: tenant-1
  mount: pki
  role: default
  destination:
    create: true
    name: pki-tls
    type: kubernetes.io/tls
  commonName: localhost
  format: pem
  revoke: true
  clear: true
  expiryOffset: 15s
  ttl: 1m
---
apiVersion: v1
kind: Pod
metadata:
  name: tls-app
  namespace: tenant-1
  labels:
    app: tls-app
spec:
  containers:
  - command:
    - /agnhost
    - netexec
    - --http-port
    - "8080"
    image: registry.k8s.io/e2e-test-images/agnhost:2.39
    name: tls-app
---
kind: Service
apiVersion: v1
metadata:
  name: tls-app-service
  namespace: tenant-1
spec:
  selector:
    app: tls-app
  ports:
    - port: 443
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tls-example-ingress
  namespace: tenant-1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
  - hosts:
    - localhost
    secretName: pki-tls
  rules:
  - host: localhost
    http:
      paths:
      - path: /tls-app(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: tls-app-service
            port:
              number: 443
