# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  labels:
    app.kubernetes.io/name: vaultdynamicsecret
    app.kubernetes.io/instance: vaultdynamicsecret-instant-updates
    app.kubernetes.io/part-of: vault-secrets-operator
  name: vaultdynamicsecret-instant-updates
spec:
  vaultAuthRef: example
  mount: database
  path: static-creds/myrole
  allowStaticCreds: true
  destination:
    name: app-db-credentials
    create: true
  syncConfig:
    instantUpdates: true
    engineType: database
