# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

---
apiVersion: v1
kind: Secret
metadata:
  name: pki1
  namespace: tenant-1
type: Opaque
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  namespace: tenant-1
  name: vaultpkisecret-sample-tenant-1
spec:
  vaultAuthRef: vaultauth-sample
  namespace: tenant-1
  mount: pki
  role: default
  destination:
    name: pki1
  commonName: consul.example.com
  format: pem
  revoke: true
  clear: true
  expiryOffset: 5s
  ttl: 15s
#---
#apiVersion: secrets.hashicorp.com/v1beta1
#kind: VaultPKISecret
#metadata:
#  namespace: tenant-2
#  name: vaultpkisecret-sample-tenant-2
#spec:
#  namespace: cluster1/tenant-2
#  mount: pki
#  role: default
#   destination:
#    name: pki1
#  commonName: consul.example.com
#  revoke: false
#  format: pem_bundle
