@startuml
'!include /Users/bash/src/github.com/plantuml-stdlib/C4-PlantUML/C4_Dynamic.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Dynamic.puml
!include sprites/secret-128-scaled.puml
!include sprites/pod-128-scaled.puml
!include sprites/HashiCorp_Logomark_White_RGB-scaled.puml

UpdateElementStyle("container", $shadowing="true")
UpdateElementStyle("person", $shadowing="true")
AddRelTag("deployer_sp", $lineColor="red", $lineStyle=BoldLine(), $lineThickness=3)
AddRelTag("deployer_app", $lineColor="#118bda", $lineStyle=BoldLine(), $lineThickness=3)
AddRelTag("vso", $lineColor="#d33716", $lineStyle=BoldLine(), $lineThickness=3)

LAYOUT_TOP_DOWN()
HIDE_STEREOTYPE()
UpdateBoundaryStyle($elementName="container", $type="k8s")

Person(user, Deployer/Agent, $sprite="person")

System_Boundary(c1, "HCP") {
    Container(app, "HCP Vault Secrets", "", "Secret Source", $sprite="HashiCorp_Logomark_White_RGB")
}

System_Boundary(c2, "Kubernetes Cluster", "") {
Container_Boundary(vso_ns, "vso-namespace") {
    Container(vso, "Vault Secrets Operator", "Pod", "Secret Lifecycle Agent", $sprite="HashiCorp_Logomark_White_RGB", $tags="ns")
}

Container_Boundary(app_ns, "app-namespace", $tags="namespace") {
Container_Boundary(c6, "App Deployment", $tags="namespace") {
    Container(pod1, "app1", "Pod", "", $sprite="pod")
}
    Container(app_secret, "app-secret", "HVS Secret Data", "", $sprite="secret")
    Container(sp_secret, "hcp-sp-auth-secret", "{clientID=client1, clientSecret=clientSecret1}", "", $sprite="secret")
}
}


Rel_D(user, sp_secret, "Apply HCP Service Principal creds YAML", "HTTPS k8s/api", $tags="deployer_app", $index=Index()-1)
Rel_D(user, vso_ns, "Apply HCPAuth CR YAML manifest", "HTTPS k8s/api", $tags="deployer_app", $index=LastIndex()-2)
Rel_R(user, app, "Create HCP Vault Secrets app1 + app_secret", "HTTPS hcp/api", $tags="deployer_app", $index=LastIndex()-3)
Rel_L(app, user, "Returns HCPVaultSecretsApp CR YAML manifest", "HTTPS hcp/api", $tags="deployer_app", $index=LastIndex()-4)
Rel_R(user, app_ns, "Apply HCPVaultSecretsApp CR YAML manifest", "HTTPS k8s/api", $tags="deployer_app", $index=LastIndex()-5)

Rel_D(vso, sp_secret, "Get HCP Auth Service Principal Creds", "HTTPS k8s/api", $tags="vso", $index=Index()-1)
Rel_U(vso, app, "Request app1 with SP Creds", "HTTPS hcp/api/app1", $tags="vso", $index=LastIndex()-2)
Rel_D(vso, app_secret, "Store app1 Response", "HTTPS k8s/api", $tags="vso", $index=LastIndex()-3)
Rel_L(pod1, app_secret, "Get Secret Data from volume/env-var", $tags="deployer_sp", $index=Index()-1)
@enduml
