// Copyright IBM Corp. 2022, 2025
// SPDX-License-Identifier: BUSL-1.1

package consts

const (
	ReasonAccepted                      = "Accepted"
	ReasonInvalidConfiguration          = "InvalidConfiguration"
	ReasonInvalidResourceRef            = "InvalidResourceRef"
	ReasonK8sClientError                = "K8sClientError"
	ReasonRolloutRestartFailed          = "RolloutRestartFailed"
	ReasonRolloutRestartTriggered       = "RolloutRestartTriggered"
	ReasonRolloutRestartTriggeredFailed = "RolloutRestartTriggeredFailed"
	ReasonRolloutRestartUnsupported     = "RolloutRestartUnsupported"
	ReasonSecretLeaseRenewal            = "SecretLeaseRenewal"
	ReasonSecretLeaseRevoke             = "SecretLeaseRevoke"
	ReasonSecretLeaseRenewalError       = "SecretLeaseRenewalError"
	ReasonSecretRotated                 = "SecretRotated"
	ReasonSecretSync                    = "SecretSync"
	ReasonSecretSyncError               = "SecretSyncError"
	ReasonSecretSynced                  = "SecretSynced"
	ReasonStatusUpdateError             = "StatusUpdateError"
	ReasonUnrecoverable                 = "Unrecoverable"
	ReasonVaultClientConfigError        = "VaultClientConfigError"
	ReasonHVSClientConfigError          = "HVSClientConfigError"
	ReasonVaultClientError              = "VaultClientError"
	ReasonVaultStaticSecret             = "VaultStaticSecretError"
	ReasonHVSSecret                     = "HVSSecretError"
	ReasonSecretDataDrift               = "SecretDataDrift"
	ReasonInexistentDestination         = "InexistentDestination"
	ReasonResourceUpdated               = "ResourceUpdated"
	ReasonInitialSync                   = "InitialSync"
	ReasonInRenewalWindow               = "InRenewalWindow"
	ReasonHMACDataError                 = "HMACDataError"
	ReasonCertificateRevocationError    = "CertificateRevocationError"
	ReasonTransformationError           = "TransformationError"
	ReasonSecretDataBuilderError        = "SecretDataBuilderError"
	ReasonForceSync                     = "ForceSync"
	ReasonVaultTokenRotated             = "VaultTokenRotated"
	ReasonVaultClientConfigChanged      = "VaultClientConfigChanged"
	ReasonEventWatcherError             = "EventWatcherError"
	ReasonEventWatcherStarted           = "EventWatcherStarted"
	ReasonHealthy                       = "Healthy"
	ReasonUnhealthy                     = "Unhealthy"
	ReasonReady                         = "Ready"
)
